baseURL = 'https://jur1st.github.io/antisocial-fiverings-photo/'
languageCode = 'en-us'
title = 'antisocial.fiverings.photo'

# Enable canonifyURLs for GitHub Pages subdirectory deployment
canonifyURLs = true

# Disable problematic features for development
disableRSS = true
disableKinds = ["RSS", "taxonomy", "term"]

[params]
  title = 'antisocial.fiverings.photo'
  description = 'Antisocial FiveRings Photography'
  author = 'John Benson'

[author]
  name = 'John Benson'
  email = 'john@darkolabs.io'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
